### ISSUE TITLE
reset to original blue

### ISSUE THREAD

**Issue by ramslamiel** [Golem642/CtrRGBPAT2#5]
it doesnt seem like i can change back to the original blue and i just want the default green notification uninstalling the program and turning it off in the program doesnt work

**Comment by Golem642** [comment]
Hello, I have a function to reset it, but it will reset **all** of the pattern changes you made.
You have 2 options :
- Reinstall the app, open it, and once in the menu press Y to enable debug mode, and then X to restore to default
- Move/delete the file at `/luma/sysmodules/0004013000003502.ips`

You can also find the default patterns in the code and try to recreate them yourself if you want

It's been a while since i worked on this, but I'll make a simple per selection reset process

**Comment by ramslamiel** [comment]
sorry this just removes the light entirely

**Comment by Golem642** [comment]
Yes that's what i said, it should remove all of your changes and reset back to the default colors and animations

**Comment by ramslamiel** [comment]
Oh my apologies cause I never checked my notifications I assumed the blue light was always meant to be there that's on me thank you for the help
